### ISSUE TITLE
Issue with downloaded_filename

### ISSUE THREAD

**Issue by h-OUS-e** [neurall/PlenoxelsColab#2]
Thank you for making this colab notebook! I am having an issue running it, it gives me this error when I try to run the code cell, and I believe it has something to do with the download link not being public anymore. Any ideas on how to fix this?
![image](https://user-images.githubusercontent.com/66432003/159146084-990327bb-20c2-42bb-ba30-6b8da4bd79ca.png)
 Thank you!

**Comment by neurall** [comment]
thx for reporting it ;)
it looks like bug in gdown according to https://github.com/wkentaro/gdown/issues/43
fixed by adding to top cell !pip install --upgrade --no-cache-dir gdown 
now downloading works as expected again it seems.
btw this colab and svox2 is obsolete. nvidia released better instant version
